steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy scrape-jobs \
          --source web_scraping_project \
          --runtime python310 \
          --trigger-http \
          --region australia-southeast1 \
          --allow-unauthenticated \
          --project web-scraper-prod \
          --service-account scraper-fn@web-scraper-prod.iam.gserviceaccount.com
          --gen=1

options:
  logging: "CLOUD_LOGGING_ONLY"
